package com.jiyibi.ledger.ui.theme

import androidx.compose.ui.graphics.Color

/* ---------------- Material Design 3 · 浅色 ---------------- */
val Primary = Color(0xFF6750A4)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFEADDFF)
val OnPrimaryContainer = Color(0xFF21005D)
val SecondaryContainer = Color(0xFFE8DEF8)
val OnSecondaryContainer = Color(0xFF1D192B)
val Surface = Color(0xFFFEF7FF)
val OnSurface = Color(0xFF1D1B20)
val SurfaceVariant = Color(0xFFE7E0EC)
val OnSurfaceVariant = Color(0xFF49454F)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF7F2FA)
val SurfaceContainer = Color(0xFFF3EDF7)
val SurfaceContainerHigh = Color(0xFFECE6F0)
val SurfaceContainerHighest = Color(0xFFE6E0E9)
val Outline = Color(0xFF79747E)
val OutlineVariant = Color(0xFFCAC4D0)
val ErrorRed = Color(0xFFB3261E)
val InverseSurface = Color(0xFF322F35)
val InverseOnSurface = Color(0xFFF5EFF7)
val MoneyOutLight = Color(0xFFB3261E)
val MoneyInLight = Color(0xFF146C2E)

/* ---------------- Material Design 3 · 深色 ---------------- */
val DarkPrimary = Color(0xFFD0BCFF)
val DarkOnPrimary = Color(0xFF381E72)
val DarkPrimaryContainer = Color(0xFF4F378B)
val DarkOnPrimaryContainer = Color(0xFFEADDFF)
val DarkSecondaryContainer = Color(0xFF4A4458)
val DarkOnSecondaryContainer = Color(0xFFE8DEF8)
val DarkSurface = Color(0xFF141218)
val DarkOnSurface = Color(0xFFE6E0E9)
val DarkSurfaceVariant = Color(0xFF49454F)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkSurfaceContainerLowest = Color(0xFF0F0D13)
val DarkSurfaceContainerLow = Color(0xFF1D1B20)
val DarkSurfaceContainer = Color(0xFF211F26)
val DarkSurfaceContainerHigh = Color(0xFF2B2930)
val DarkSurfaceContainerHighest = Color(0xFF36343B)
val DarkOutline = Color(0xFF938F99)
val DarkOutlineVariant = Color(0xFF49454F)
val DarkErrorRed = Color(0xFFF2B8B5)
val DarkInverseSurface = Color(0xFFE6E0E9)
val DarkInverseOnSurface = Color(0xFF322F35)
val MoneyOutDark = Color(0xFFF2B8B5)
val MoneyInDark = Color(0xFF7EDFA0)
